name: Cleanup Old Deployments

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Deployments
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/pages/deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
