name: Cleanup Old Deployments

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Deployments
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          "https://api.github.com/repos/${{ github.repository }}/pages"
